### ISSUE TITLE
PDG) 컴퓨터 클래스의 stop 함수를 구현한다.

### ISSUE THREAD

**Issue by geonxee** [shinhan-team/pigdicegame#10]
## 요약
컴퓨터 클래스의 stop 함수 구현하기

## 할 일
-[ ] 함수가 호출되었을 때, now_score를 total_score에 저장한다.
-[ ] total_score가 50점이 넘었을 경우, 게임을 종료한다.
-[ ] 다음 사람의 턴으로 옮긴다.

**Comment by kingwangzzang1234** [comment]
`- [ ]`의 형태가 되어야
- [x] 처럼 체크박스가 만들어집니다 ㅎ
